Add did:btco driver.
decentralized-identity/universal-resolver pull request #388
Opened 2023-12-04 06:42 UTC by brianorwhatever

This PR will be ready once the explorer at https://signet.ordinals.com has been updated to the latest release and I have tested the resolver against infrastructure I don't control.

2023-12-21 19:45 UTC, peacekeeper commented
Hello @brianorwhatever thanks for working on this; looking forward to adding support for did:btco !

2023-12-23 05:49 UTC, brianorwhatever commented
This is now ready for review the did spec registry PR is here https://github.com/w3c/did-spec-registries/pull/541

2023-12-29 21:06 UTC, peacekeeper commented
@brianorwhatever When I try this, I get the following error:

```
 ! driver-did-btco The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested                        0.0s 
Attaching to universal-resolver-driver-did-btco-1, universal-resolver-uni-resolver-web-1
universal-resolver-driver-did-btco-1   | exec /usr/local/bin/docker-entrypoint.sh: exec format error
universal-resolver-driver-did-btco-1 exited with code 1
```

I don't have much experience with supporting different platforms in Docker.. Do you know how to fix this? Maybe the image has to be built in a different way?

2023-12-31 05:09 UTC, brianorwhatever commented
@peacekeeper I can build it on a different platform. What should I use? I'm guessing `linux/amd64`?

2023-12-31 09:31 UTC, peacekeeper commented
Yes that would be good, thanks!

2024-02-16 23:59 UTC, kimdhamilton requested changes
Hi Brian, as part of Universal Resolver stability improvements, we're requiring use of a specific image version rather than "latest" (i.e. `brianrichter/did-btco:latest`). Can you tag it with a version and update the PR?

2024-02-28 16:24 UTC, ankurdotb requested changes

2024-02-28 16:24 UTC, ankurdotb commented on docker-compose.yml
> +    image: brianrichter/did-btco:latest
Only tag available is `latest`. Ideally, please tag and push an image to a Docker registry with a semantic version number.

2024-11-05 08:48 UTC, peacekeeper commented
Hello @brianorwhatever, following up on this, would it be possible to update this PR with a stable driver version?

2025-05-09 16:53 UTC, closed without merging