feat: New driver `did:algo`
decentralized-identity/universal-resolver pull request #409
Opened 2024-03-01 01:18 UTC by bcessa

Documentation is available at:
https://github.com/algorandfoundation/did-algo/blob/main/DRIVER.md

2024-03-01 02:23 UTC, dif-admin commented on docker-compose.yml
> +    image: ghcr.io/aidtechnology/algoid-resolver:latest
Replace with tagged version

2024-03-01 02:25 UTC, dif-admin requested changes
Thanks for this PR @bcessa! 
One small update: we no longer support use of the "latest" tag; can you please replace this?

2024-03-01 16:53 UTC, bcessa commented
> Thanks for this PR @bcessa! One small update: we no longer support use of the "latest" tag; can you please replace this?

Thanks for pointing it out @dif-admin 👏🏼 we added the image tag (`0.6.0`) now.

2024-03-01 16:58 UTC, peacekeeper requested changes
This seems to make some changes to other driver configs, replacing `"` with `'` characters in `application.yml`. Could you change the PR to only add your driver, without making changes to other drivers?

2024-03-01 17:04 UTC, bcessa commented
> This seems to make some changes to other driver configs, replacing `"` with `'` characters in `application.yml`. Could you change the PR to only add your driver, without making changes to other drivers?

You are right @peacekeeper was unintended, should be reverted now.

2024-03-02 07:39 UTC, peacekeeper approved these changes
Thanks looks good!

2024-03-04 11:28 UTC, merged